---
nextcloud_exporters:
  - name: ejtcloud
    url: https://www.ejtcloud.de
    token: "{{ lookup('gopass', 'websites/www.ejtcloud.de/serverinfo-token') }}"
    port: 9205

  - name: heuselcloud
    url: https://cloud.heusel.eu
    token: "{{ lookup('gopass', 'cloud-heusel-eu-serverinfo-token') }}"
    port: 9206

fritzbox_exporter:
  username: fritzbox-exporter
  password: "{{ lookup('gopass', 'heuselfamily/fritzbox-exporter') }}"
  gateway_url: http://192.168.71.1:49000
  listen_port: 9042

mosquitto_exporters:
  - name: broker
    port: 9234
    url: tcp://scotty-the-fifth.chris.vpn.heusel.eu:1883
    user: "mosquitto-exporter"
    password: "{{ lookup('gopass', 'heuselfamily/mqtt/mosquitto-exporter') }}"
    client_id: "mosquitto-exporter"
