---
# tasks file for mosquitto-exporter

- name: checkout the repo
  ansible.builtin.git:
    repo: 'https://github.com/christian-heusel/mosquitto-exporter.git'
    dest: "{{ mosquitto_exporter_project_dir }}"

- name: create the docker-compose project
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ (mosquitto_exporter_project_dir, 'docker-compose.yml') | path_join }}"

- name: set up the docker-compose project
  community.docker.docker_compose:
    project_src: "{{ mosquitto_exporter_project_dir }}"
    state: present
