---
# tasks file for mosquitto-exporter

- name: install the exporter
  kewlfft.aur.aur:
    name: prometheus-mosquitto-exporter-git
    use: makepkg
    state: present
    aur_only: yes

- name: set the exporter vars
  ansible.builtin.template:
    src: conf.j2
    dest: "/etc/conf.d/prometheus-mosquitto-exporter"
  notify: restart the mosquitto exporter

- name: start & enable the exporter
  ansible.builtin.systemd:
    name: "prometheus-mosquitto-exporter.service"
    enabled: yes
